[build]
  publish = "."
  command = "npm run build"

[dev]
  publish = "."
  port = 3000

# Handle SPA routing - redirect all requests to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Explicitly serve static files from the public directory
[[redirects]]
  from = "/public/*"
  to = "/public/:splat"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  NODE_ENV = "production"