[build]
  publish = "."
  command = ""

[dev]
  publish = "."
  port = 3000

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[[redirects]]
  from = "/profile.png"
  to = "/profile.png"
  status = 200
  force = false

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
